logging:
  level: INFO
  loggers:
    com.exemploDB: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: rmro
  url: jdbc:postgresql://localhost:5432/enotas_db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  validationQuery: "SELECT 1"